{
  "run": {
    # timeout for analysis, e.g. 30s, 5m, default is 1m
    "timeout": "3m",
  },
  "linters": {
    "fast": false,
    "enable": [
      "errcheck",
      "gosec",
      "gocritic",
      "gofmt",
      "goimports",
      "gosimple",
      "govet",
      "ineffassign",
      "misspell",
      "nakedret",
      "revive",
      "staticcheck",
      "unconvert",
      "unparam",
      "unused",
    ],
  },
  "disable": [
    "depguard",
    "dupl",
    "gocyclo",
    "interfacer",
    "lll",
    "maligned",
    "prealloc",
    "typecheck",
  ],
  "linters-settings": {
    "gocritic": {
      "enabled-checks": [
        "ruleguard",
      ],
      "settings": {
        "ruleguard": {
          "rules": "rules.go",
        },
      },
    },
  },
  "issues": {
    "exclude-dirs": ["checkers/rules"],
  }
}
