version: "2"
linters:
  enable:
    - copyloopvar
    - gocritic
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
    - usetesting
  disable:
    - depguard
    - dupl
    - gocyclo
    - lll
    - prealloc
  settings:
    gocritic:
      enabled-checks:
        - ruleguard
      settings:
        ruleguard:
          rules: rules.go
    gosec:
      excludes:
        - G115
    usetesting:
      os-temp-dir: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goprintffuncname
        text: (?i)Warn(WithPos|Fixable)?
    paths:
      - checkers/rules
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - checkers/rules
      - third_party$
      - builtin$
      - examples$
