{
  "run": {
    # timeout for analysis, e.g. 30s, 5m, default is 1m
    "timeout": "3m",
  },
  "linters": {
    "fast": false,
    "enable": [
      "copyloopvar",
      "errcheck",
      "gosec",
      "gocritic",
      "gofmt",
      "goimports",
      "goprintffuncname",
      "gosimple",
      "govet",
      "ineffassign",
      "misspell",
      "nakedret",
      "revive",
      "staticcheck",
      "unconvert",
      "unparam",
      "unused",
      "usetesting",
    ],
    "disable": [
      "depguard",
      "dupl",
      "gocyclo",
      "lll",
      "prealloc",
    ],
  },
  "linters-settings": {
    "gocritic": {
      "enabled-checks": [
        "ruleguard",
      ],
      "settings": {
        "ruleguard": {
          "rules": "rules.go",
        },
      },
    },
    "gosec": {
      "excludes": ["G115"]
    },
    "usetesting": {
      "os-temp-dir": true,
    },
  },
  "issues": {
    "exclude-case-sensitive": true,
    "exclude-dirs": ["checkers/rules"],
    "exclude-rules": [
      # Backward compatibility for CheckerContext.Warn, WarnWithPos, WarnFixable, and WarnFixableWithPos
      {"linters":["goprintffuncname"], "text":"Warn(WithPos|Fixable)?"},
    ]
  }
}
