{
  "run": {
    # timeout for analysis, e.g. 30s, 5m, default is 1m
    "deadline": "3m",
    "skip-dirs": ["checkers/rules"],
  },
  "fast": false,
  "linters": {
    "enable": [
      "deadcode",
      "errcheck",
      "gas",
      "gocritic",
      "gofmt",
      "goimports",
      "golint",
      "gosimple",
      "govet",
      "ineffassign",
      "megacheck",
      "misspell",
      "nakedret",
      "staticcheck",
      "structcheck",
      "unconvert",
      "unparam",
      "unused",
      "varcheck",
    ],
  },
  "disable": [
    "depguard",
    "dupl",
    "gocyclo",
    "interfacer",
    "lll",
    "maligned",
    "prealloc",
    "typecheck",
  ],
  "linters-settings": {
    "gocritic": {
      "enabled-checks": [
        "ruleguard",
      ],
      "settings": {
        "ruleguard": {
          "rules": "rules.go",
        },
      },
    },
  },
}
