// Code generated by "goosChecker_gen/gen.go". DO NOT EDIT.
// Source: go1.26.1 ($GOROOT/src/internal/syslist/syslist.go)

package checkers

var knownGOOS = map[string]bool{
	"aix": true,
	"android": true,
	"darwin": true,
	"dragonfly": true,
	"freebsd": true,
	"hurd": true,
	"illumos": true,
	"ios": true,
	"js": true,
	"linux": true,
	"nacl": true,
	"netbsd": true,
	"openbsd": true,
	"plan9": true,
	"solaris": true,
	"wasip1": true,
	"windows": true,
	"zos": true,
}
