//go:build generate

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"
)

var outputTemplate = template.Must(template.New("syslist").Parse(`// Code generated by "goosChecker_gen/gen.go". DO NOT EDIT.
// Source: {{.GoVersion}} ({{.GOROOT}}/src/internal/syslist/syslist.go)

package checkers

var knownGOOS = map[string]bool{
{{- range .GOOS}}
	{{printf "%q" .}}: true,
{{- end}}
}
`))

func main() {
	log.SetFlags(0)
	if err := run(); err != nil {
		log.Fatalf("error: %v", err)
	}
}

func run() error {
	goroot := flag.String("goroot", "", "path to GOROOT")
	output := flag.String("o", "", "output file path")
	flag.Parse()

	if *goroot == "" {
		return fmt.Errorf("-goroot is required")
	}
	if *output == "" {
		return fmt.Errorf("-o is required")
	}

	syslistPath := filepath.Join(*goroot, "src", "internal", "syslist", "syslist.go")
	src, err := os.ReadFile(syslistPath)
	if err != nil {
		return fmt.Errorf("read syslist.go: %v", err)
	}

	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, syslistPath, src, 0)
	if err != nil {
		return fmt.Errorf("parse syslist.go: %v", err)
	}

	goos, err := extractMapKeys(f, "KnownOS")
	if err != nil {
		return err
	}

	sort.Strings(goos)

	goVersion := readGoVersion(*goroot)

	var buf bytes.Buffer
	err = outputTemplate.Execute(&buf, map[string]interface{}{
		"GOOS":      goos,
		"GoVersion": goVersion,
		"GOROOT":    "$GOROOT",
	})
	if err != nil {
		return fmt.Errorf("execute template: %v", err)
	}

	if err := os.WriteFile(*output, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write output: %v", err)
	}

	return nil
}

func readGoVersion(goroot string) string {
	data, err := os.ReadFile(filepath.Join(goroot, "VERSION"))
	if err != nil {
		return "unknown"
	}
	// VERSION file has the version on the first line (e.g. "go1.26.1").
	version, _, _ := strings.Cut(string(data), "\n")
	return strings.TrimSpace(version)
}

func extractMapKeys(f *ast.File, varName string) ([]string, error) {
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.VAR {
			continue
		}
		for _, spec := range gd.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok || len(vs.Names) == 0 || vs.Names[0].Name != varName {
				continue
			}
			if len(vs.Values) == 0 {
				return nil, fmt.Errorf("variable %s has no initializer", varName)
			}
			cl, ok := vs.Values[0].(*ast.CompositeLit)
			if !ok {
				return nil, fmt.Errorf("variable %s is not a composite literal", varName)
			}
			var keys []string
			for _, elt := range cl.Elts {
				kv, ok := elt.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				bl, ok := kv.Key.(*ast.BasicLit)
				if !ok || bl.Kind != token.STRING {
					continue
				}
				s, err := strconv.Unquote(bl.Value)
				if err != nil {
					continue
				}
				keys = append(keys, s)
			}
			return keys, nil
		}
	}
	return nil, fmt.Errorf("variable %s not found", varName)
}
