name: Doc

on:
  push:
    branches: [master]

jobs:
  generate_doc:
    name: generate_doc
    runs-on: ubuntu-latest
    env:
      PATH_OVERVIEW: './docs/overview.md'
    permissions:
      contents: write

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          ref: ${{ github.head_ref }}
          go-version: stable
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Generate docs
        run: |
          make docs

      - name: Commit into master
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: auto generate doc
          file_pattern: ${{ env.PATH_OVERVIEW }}

      - name: Call of hook if doc changed
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          overview=$(xz -z --stdout "${{ env.PATH_OVERVIEW }}" | base64) 
          gh auth login --with-token <<< "${TOKEN}"
          gh api repos/Lasiar/go-critic.github.io/dispatches \
            --field "event_type='update_doc'" \
            --field "client_payload[content]="${overview}""
