name: Doc

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  generate_doc:
    name: generate_doc
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        go: ['stable']

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: stable
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Make docs
        run: |
          make docs

      - uses: stefanzweifel/git-auto-commit-action@v5
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          commit_message: generate docs.

