name: Doc

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  generate_doc:
    name: generate_doc
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        go: ['stable']

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          ref: ${{ github.head_ref }}
          go-version: stable
          check-latest: true

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Make docs
        run: |
          make docs

      - uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          commit_message: auto generate doc
          file_pattern: ./docs/overview.md

      - name: "Run if changes have been detected"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          file=$(xz -z --stdout ./docs/overview.md | base64) 
          gh api repos/Lasiar/go-critic.github.io/dispatches \
            --field event_type='update_doc' \
            --field 'client_payload[content]=test'
